encoding: "positional_encoding" # "gaussian_mapping"
positional_encoding:
  input_size: 120
gaussian_mapping:
  input_size: 256

training:
  num_epochs: 30
  batch_size: 4096

reconstruction:
  voxel_size: [66, 79, 66]