encoding: "positional_encoding" # "gaussian_mapping"
positional_encoding:
  input_size: 120
  scale: 10000
gaussian_mapping:
  input_size: 256
  scale: 10

training:
  num_epochs: 100
  batch_size: 2500
  eval_existing_model: True

reconstruction:
  voxel_size: [66, 79, 66]